spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - https://deungsanlog.site
              - http://localhost:8080  # ⭐ 내부 프록시 통신 허용
              - http://127.0.0.1:8080

            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.oauth.client-id}
            client-secret: ${google.oauth.client-secret}
            scope:
              - email
              - profile
            # redirect-uri 제거 - keys에서 가져옴
          naver:
            client-id: ${naver.oauth.client-id}
            client-secret: ${naver.oauth.client-secret}
            client-name: Naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            # redirect-uri 제거 - keys에서 가져옴
          kakao:
            client-id: ${kakao.oauth.client-id}
            client-secret: ${kakao.oauth.client-secret}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
            # redirect-uri 제거 - keys에서 가져옴

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

frontend:
  redirect-uri: https://deungsanlog.site/login