spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
              - http://localhost:8080
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.oauth.client-id}
            client-secret: ${google.oauth.client-secret}
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/auth/google/callback
          naver:
            client-id: ${naver.oauth.client-id}
            client-secret: ${naver.oauth.client-secret}
            client-name: Naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            redirect-uri: http://localhost:8080/auth/naver/callback

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

frontend:
  redirect-uri: http://localhost:5173/login
