spring:
  profiles:
    active: dev  # 개발 시에는 dev, 배포 시에는 prod 로 바꿈
    include: keys

logging:
  file:
    name: logs/gateway-service.log
    path: logs

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.web.reactive: DEBUG
