spring:
  application:
    name: mountain-service
  profiles:
    active: dev
    include: keys
  config:
    import: application-keys.yml

  datasource:
    url: jdbc:mysql://14.63.178.148:${db.port}/deungsanlog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 10000
      max-lifetime: 30000
      leak-detection-threshold: 10000

  batch:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

publicdata:
  api:
    key: ${publicdata.api.key}

logging:
  file:
    name: logs/mountain-service.log
  level:
    root: INFO