spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deungsanlog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true


publicdata:
  api:
    key: "ZiU0Hc7qxDyQuMi893rfDHYGec2zUAcA1P1afKzVfb%2BXLPelpqmlKadv5zZx5xSjBqAcBJe5kHR5PDQua9OHEg%3D%3D"

